/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRollingDice(){
        int[] output = new Library().rollingDice(1);
        boolean isOk = false;
        if(output[0] == 1 || output[0] == 2 || output[0] ==3){ // check 1 - 6
            isOk = true;
        }
        assertTrue("the first element should be a possible number on a dice", isOk);
    }
}
