/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksAndQueues;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Node first = new Node(1);
        Node second = new Node(2, null);
        Node third = new Node(3, second);

        Stack<Integer> s = new Stack<Integer>();
        s.add(9);
        s.add(10);
        s.add(11);

        Stack<String> strings = new Stack<>();
        strings.add("world");
        strings.add("hello");

        System.out.println(s.toString());
        System.out.println(strings.toString());
        System.out.println(strings.pop());
        System.out.println(strings.pop());




    }
}
