import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        for(String arg : args) {
            System.out.println(arg);
        }
        // find an image
        Path imagePath = FileSystems.getDefault().getPath("resources", args[0]);
//        FileSystems.getDefault().getPath()
        // read the image
        Bitmap bmp = new Bitmap(imagePath);
        // mess with the image

        if(args[2].equals("h")){
            bmp.flipHorizontally();

        } else {
            bmp.flipVertically();
        }
        // output the image

        bmp.save(FileSystems.getDefault().getPath("resources", args[1]));
    }
}
