/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class ShelterTest {
    @Test public void testShelter() {
        assertTrue("someLibraryMethod should return 'true'", true);

        Horse horsey = new Horse("lil sebastien");
//        System.out.println(
//                Arrays.toString(horsey.checkEnemies(new String[]{"tiger", "lion", "giraffe", "cat", "dog"}))
//        );

        Cat garfield = new Cat();

//        System.out.println(
//                Arrays.toString(garfield.checkEnemies(new String[]{"tiger", "lion", "giraffe", "cat", "dog"}))
//        );

        ShelterableAnimal[] shelteredAnimals = {horsey, garfield, new Horse("bojak",  new String[]{"pigs"})};

        for( ShelterableAnimal animal : shelteredAnimals){
            System.out.println(
                    Arrays.toString(animal.checkEnemies(new String[]{"tiger", "lion", "giraffe", "cat", "dog"}))
            );

//            System.out.println(animal.name);

        }

    }
}
