/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package internetdemo;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        URL url = null;
        try {
            url = new URL("http://numbersapi.com/20");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer content = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();

            System.out.println(content.toString());

        } catch (IOException e) {
            System.out.println("1 is the number of hair that nicholas has");
        }


    }
}
