/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import static java.lang.System.*;


public class Library {
    public boolean someLibraryMethod() {
        out.println(new java.util.Date());
        return true;
    }
}
