/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Scanner;

public class Library {
    public boolean someLibraryMethod() {
        ArrayList<String> characters = new ArrayList<>();
        characters.add("Alice");
        characters.add("Mouse");
        characters.add("Hatter");
        characters.add("Rabbit");
        characters.add("Caterpillar");

        HashMap<String, Integer> characterCount = new HashMap<>();

        // HashSet is I want a list of things that are all unique, that are quick to look up
        HashSet<String> alsoCharacters = new HashSet<>(characters);

        // start each character with 0 times seen
        for(String character : alsoCharacters){
            characterCount.put(character, 0);
        }

        // Iterate over every word of the book and see if it is a character I am looking for
        Scanner book;
        try {
            book = new Scanner(new File("src/main/resources/alice.txt"));
            while(book.hasNext()){

                String text = book.next();
                if(alsoCharacters.contains(text)){
//                    System.out.println(text);
                    characterCount.put(text, characterCount.get(text) + 1);
                }
            }

            for( String character : characterCount.keySet()){
                System.out.println(character + " was mentioned " + characterCount.get(character) + " times");
            }

        } catch(FileNotFoundException exception){
            System.out.println("You didnt find the file, maybe next time");
        }




        return true;
    }
}
