/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day2library;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    // annotation
    @Test public void testSomeLibraryMethod() {

        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod()); // true
        assertTrue("this is not going to be true, but should", true);

        //assert means "it must be"
        char[] chars = {'a','b','d'};
        // find suggestions "alt + enter"
        assertArrayEquals(chars, new char[]{'a', 'b', 'c'});

    }

    @Test public void testSayHi(){
        Library libraryToTest = new Library();

//        assertEquals("a hi message should say hello and something nice", "Hey there, Ranjit you are so cool!", libraryToTest.sayHello("Ranjit "));
    }

    public void doNothing(){

    }
}
