/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day2library;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String sayHello(String name){
        return "Hey there, " + name + " you are so cool!";
    }
}
